import { Translations } from './types.js';

export const APP_VERSION = '1.5.0';
export const getExchangeRate = () => (window as any).env?.EXCHANGE_RATE || 0;
export const getShippingCost = () => (window as any).env?.SHIPPING_COST_CENTS || 0;
export const getMinCartSubtotal = () => (window as any).env?.MIN_CART_SUBTOTAL_CENTS || 0;
export const DEFAULT_IMG_CACHE = 100;
export const MAX_IMGS = 1000;
export const MAX_IMG_CACHE_PERCENT = 0.25;

export const PLANT_CLASSES = ["Opuntia", "Euphorbia", "Mammillaria", "Aizoaceae", "Aloe", "Crassula", "Echeveria", "Haworthia", "Sansevieria", "Sedum", "Sempervivum"];

export const THEME = {
    primary: 'var(--primary)',
    secondary: 'var(--secondary)',
    success: 'var(--success)',
    successDark: 'var(--success-dark)',
    danger: 'var(--danger)',
    warning: 'var(--warning)',
    info: 'var(--info)',
    light: 'var(--light)',
    dark: 'var(--dark)',
    white: 'var(--white)',
    black: 'var(--black)',
    gray100: 'var(--gray-100)',
    gray200: 'var(--gray-200)',
    gray300: 'var(--gray-300)',
    gray400: 'var(--gray-400)',
    gray500: 'var(--gray-500)',
    gray600: 'var(--gray-600)',
    gray700: 'var(--gray-700)',
    gray800: 'var(--gray-800)',
    gray900: 'var(--gray-900)',
    text: 'var(--text)',
    textMuted: 'var(--text-muted)',
    border: 'var(--border)',
    overlay: 'var(--overlay)',
    searchBg: 'var(--search-bg)',
    adminBg: 'var(--admin-bg)',
};

export const translations: Translations = {
    en: {
        logout: "Logout",
        addItem: "Add Item",
        help: "Help",
        cart: "Cart",
        heroTitle: "Rare & Exotic Cacti",
        heroSubtitle: "Delivered safely from our nursery to your doorstep.",
        inventoryTitle: "Current Inventory",
        uploadTitle: "Upload New Cactus",
        labelName: "Cactus Name",
        labelPrice: "Price ($)",
        labelImage: "Image URL",
        helperText: "(For demo, right click any image on Google Images and 'Copy Image Address')",
        btnAddInventory: "Add to Inventory",
        btnUpdateProduct: "Update Product",
        btnCancel: "Cancel",
        btnSave: "Save",
        loginTitle: "Cactus Studio Login",
        loginPlaceholder: "Enter WhatsApp Number",
        btnLogin: "Login",
        cartTitle: "CART",
        btnRemoveAll: "Remove All",
        cartEmpty: "Your cart is empty.",
        cartTotal: "TOTAL:",
        btnCheckout: "CHECKOUT",
        btnAddCart: "Add to Cart",
        btnRemove: "Remove",
        alertAccessGranted: "Admin access granted.",
        alertIncorrectPass: "Incorrect Password.",
        alertValidNumber: "Please enter a valid number.",
        alertUpdated: "Cactus updated!",
        alertAdded: "Cactus added to inventory!",
        alertFillFields: "Please fill in all fields.",
        alertPayment: "This would go to payment!",
        prev: "Prev",
        next: "Next",
        modalAddCart: "Add to Cart +",
        outOfStock: "Out of Stock",
        itemInCart: "Item in Cart",
        btnSync: "Sync DB",
        btnMigrate: "Run Migration",
        btnUploadImages: "Upload Images",
        btnExport: "Export Products",
        btnBackup: "Backup Full DB",
        btnRestore: "Restore FullDB",
        btnUpload: "📤 Upload",
        btnPrev: "Prev",
        btnNext: "Next",
        opt5Page: "5 / page",
        opt10Page: "10 / page",
        opt20Page: "20 / page",
        noAccount: "Don't have an account?",
        registerLink: "Register here",
        hasAccount: "Already have an account?",
        loginLink: "Login here",
        registerTitle: "Create Account",
        btnRegister: "Register",
        filterLabel: "Filter:",
        allOption: "All",
        alertLangChange: "Changing language will reload the page. Continue?",
        btnProfile: "Profile",
        profileTitle: "My Profile",
        labelPhone: "Phone",
        labelAddress: "Shipping Address",
        btnSaveProfile: "Save Changes",
        changePasswordTitle: "Change Password",
        labelCurrentPassword: "Current Password",
        labelNewPassword: "New Password",
        btnChangePassword: "Update Password",
        forgotPasswordLink: "Forgot Password?",
        resetPasswordTitle: "Reset Password",
        resetPasswordDesc: "Enter your email to receive a reset link.",
        btnSendReset: "Send Reset Link",
        backToLogin: "Back to Login",
        alertResetSent: "If an account exists with that email, a reset link has been sent.",
        placeholderEmail: "Email",
        placeholderPassword: "Password",
        placeholderPasswordConfirm: "Confirm Password",
        placeholderName: "Full Name",
        placeholderAddress: "Shipping Address",
        placeholderNewPassMin: "Password (min 8 chars, 1 upper, 1 number, 1 special)",
        alertDiscountInvalid: "Invalid discount code.",
        alertDiscountApplied: "Discount applied!",
        strengthLabel: "Strength",
        strengthWeak: "Weak",
        strengthMedium: "Medium",
        strengthStrong: "Strong",
        strengthVeryStrong: "Very Strong",
        alertPasswordRequirements: "Password must be at least 8 characters, with 1 uppercase, 1 number, and 1 special char",
        alertEmailPasswordRequired: "Email and password are required",
        alertRegisterRequired: "Email, Password, Phone, and Shipping Address are required.",
        alertEmailRequired: "Email is required",
        alertPasswordsDoNotMatch: "Passwords do not match",
        alertRegistrationSuccess: "Registration successful! Please login.",
        alertRegistrationFailed: "Registration failed.",
        alertLoginFailed: "Login failed.",
        alertVerifyEmail: "Your email is not verified. Do you want to send a new verification code?",
        alertVerificationSent: "Verification code sent! Please check your email.",
        alertResetError: "Error sending reset link.",
        alertNetworkError: "Network error.",
        alertPasswordChanged: "Password changed successfully!",
        alertFillPasswordFields: "Please fill in both password fields.",
        loadingLogin: "Logging in...",
        loadingRegister: "Registering...",
        loadingSending: "Sending...",
        loadingChangingPass: "Changing password...",
        searchPlaceholder: "Search...",
        discountCode: "Discount Code",
        apply: "Apply",
        subtotal: "Subtotal",
        discount: "Discount",
        removeDiscount: "Remove discount",
        checkingStock: "Checking Stock...",
        outOfStockRemoved: "The following items are out of stock and have been removed from your cart:",
        paymentError: "An error occurred during payment.",
        paymentCancel: "Checkout Cancelled",
        alertShippingAddressRequired: "Please provide a shipping address before checking out.",
        alertNoActiveDiscounts: "You have no active discounts.",
        alertDiscountNotAssigned: "Discount code not found in your account.",
        alertDiscountNotActive: "Discount code is not active.",
        alertCartItemsRemoved: "Some items were removed from your cart because they are no longer available.",
        alertTransactionSuccess: "Transaction completed by {name}!",
        alertPaymentSavedError: "Payment successful, but there was an error saving the receipt.",
        alertProfileUpdated: "Profile updated successfully!",
        errorValidatingDiscount: "Error validating discount code.",
        dragDropImage: "Drag & Drop Image Here",
        clickDropReplace: "Click or Drop to Replace",
        noResultsTitle: "Sorry! We couldn't find what you are searching for.",
        noResultsText: "Try adjusting your search terms.",
        labelMatchName: "Name",
        labelMatchSci: "Scientific",
        labelMatchPrice: "Price",
        labelMatchSku: "SKU",
        labelMatchMatched: "Matched",
        btnOtherPayment: "Other Payment",
        modalOtherPaymentTitle: "Manual Payment",
        labelReceiptImage: "Receipt Image",
        dropReceiptHere: "Drop receipt image here, paste (Ctrl+V), or click to upload",
        btnConfirmPurchase: "Confirm Purchase",
        alertReceiptRequired: "Please upload a receipt image.",
        alertManualOrderSuccess: "Order placed successfully! We will review your receipt.",
        btnOrders: "Orders",
        ordersTitle: "Pending Orders",
        noOrders: "No pending orders found.",
        noOrdersFound: "No {0} found.",
        headerOrder: "Order",
        headerCustomer: "Customer",
        headerTotal: "Total",
        headerStatus: "Status",
        headerShipped: "Shipped?",
        btnUpdateOrders: "Update Orders",
        alertOrdersUpdated: "Orders updated successfully!",
        viewReceipt: "View Receipt",
        btnVerify: "Verify Payment",
        btnUnverify: "Unverify Payment",
        receiptModalTitle: "Verify Receipt",
        alertOrderVerified: "Order verified! Status updated to processing.",
        alertOrderUnverified: "Order unverified! Status updated to manual verification.",
        labelPayPal: "PayPal Info",
        labelUser: "User Info",
        labelShipping: "Shipping",
        labelDate: "Date Created",
        labelShippedAt: "Date Shipped",
        statusActive: "Action Required",
        statusAll: "All Orders",
        statusShipped: "Shipped Orders",
        statusCancelled: "Cancelled Orders",
        statusRefunded: "Refunded Orders",
        statusPending: "Pending Payment",
        statusManual: "Manual Verification",
        btnShip: "Ship Order",
        btnCancelOrder: "Cancel Order",
        alertOrderShipped: "Order marked as shipped!",
        alertOrderCancelled: "Order cancelled and inventory restored.",
        confirmShip: "Mark this order as shipped?",
        confirmCancelOrder: "Are you sure you want to cancel this order? Inventory will be restored.",
        alertMinSubtotal: "Cart subtotal must be at least ${usd} / ₡{crc}.",
        labelCode: "Code",
        labelTotal: "Total",
        labelItems: "Items",
        loadingItems: "Loading items...",
        btnClose: "Close",
        labelPayPalId: "PayPal ID",
        noItemsInOrder: "No items found for this order.",
        errorLoadingItems: "Error loading items.",
        alertReceiptUploadFailed: "Receipt upload failed: ",
        alertOrderPlacementFailed: "Failed to place order: ",
        alertPaymentSystemError: "Payment system loading error. Please try again.",
        alertPaymentConfigError: "Payment configuration missing (Client ID).",
        noAddressProvided: "No address provided",
        alertLoginError: "Login failed: ",
        alertRegistrationError: "Registration failed: ",
        alertVerificationSendError: "Failed to send verification code",
        unknownError: "Unknown error",
        contactTitle: "Contact Us",
        labelSubject: "Subject",
        labelMessage: "Message",
        btnSend: "Send",
        alertMessageSent: "Message sent successfully!",
        alertMessageFailed: "Failed to send message.",
        contactBtn: "Contact Us",
    },
    es: {
        logout: "Cerrar Sesión",
        addItem: "Agregar Item",
        help: "Ayuda",
        cart: "Carrito",
        heroTitle: "Cactus Raros y Exóticos",
        heroSubtitle: "Entregados con seguridad desde nuestro vivero a tu puerta.",
        inventoryTitle: "Inventario Actual",
        uploadTitle: "Subir Nuevo Cactus",
        labelName: "Nombre del Cactus",
        labelPrice: "Precio ($)",
        labelImage: "URL de Imagen",
        helperText: "(Para demo, clic derecho en cualquier imagen de Google y 'Copiar dirección de imagen')",
        btnAddInventory: "Agregar al Inventario",
        btnUpdateProduct: "Actualizar Producto",
        btnCancel: "Cancelar",
        btnSave: "Guardar",
        loginTitle: "Login Cactus Studio",
        loginPlaceholder: "Ingresa número de WhatsApp",
        btnLogin: "Entrar",
        cartTitle: "CARRITO",
        btnRemoveAll: "Vaciar Carrito",
        cartEmpty: "Tu carrito está vacío.",
        cartTotal: "TOTAL:",
        btnCheckout: "PAGO",
        btnAddCart: "Agregar al Carrito",
        btnRemove: "Eliminar",
        alertAccessGranted: "Acceso de admin concedido.",
        alertIncorrectPass: "Contraseña incorrecta.",
        alertValidNumber: "Por favor ingresa un número válido.",
        alertUpdated: "¡Cactus actualizado!",
        alertAdded: "¡Cactus agregado al inventario!",
        alertFillFields: "Por favor llena todos los campos.",
        alertPayment: "¡Esto iría al pago!",
        prev: "Ant",
        next: "Sig",
        modalAddCart: "Agregar al Carrito +",
        outOfStock: "Agotado",
        itemInCart: "En el Carrito",
        btnSync: "Sincronizar BD",
        btnMigrate: "Ejecutar Migración",
        btnUploadImages: "Subir Imágenes",
        btnExport: "Exportar Productos",
        btnBackup: "Respaldo Completo BD",
        btnRestore: "Restaurar Completo BD",
        btnUpload: "📤 Subir",
        btnPrev: "Ant",
        btnNext: "Sig",
        opt5Page: "5 / pág",
        opt10Page: "10 / pág",
        opt20Page: "20 / pág",
        noAccount: "¿No tienes cuenta?",
        registerLink: "Regístrate aquí",
        hasAccount: "¿Ya tienes cuenta?",
        loginLink: "Inicia sesión aquí",
        registerTitle: "Crear Cuenta",
        btnRegister: "Registrar",
        filterLabel: "Filtrar:",
        allOption: "Todos",
        alertLangChange: "Cambiar el idioma recargará la página. ¿Continuar?",
        btnProfile: "Perfil",
        profileTitle: "Mi Perfil",
        labelPhone: "Teléfono",
        labelAddress: "Dirección de Envío",
        btnSaveProfile: "Guardar Cambios",
        changePasswordTitle: "Cambiar Contraseña",
        labelCurrentPassword: "Contraseña Actual",
        labelNewPassword: "Nueva Contraseña",
        btnChangePassword: "Actualizar Contraseña",
        forgotPasswordLink: "¿Olvidaste tu contraseña?",
        resetPasswordTitle: "Restablecer Contraseña",
        resetPasswordDesc: "Ingresa tu email para recibir un enlace.",
        btnSendReset: "Enviar Enlace",
        backToLogin: "Volver al Login",
        alertResetSent: "Si existe una cuenta con ese email, se ha enviado un enlace.",
        placeholderEmail: "Correo Electrónico",
        placeholderPassword: "Contraseña",
        placeholderPasswordConfirm: "Confirmar Contraseña",
        placeholderName: "Nombre Completo",
        placeholderAddress: "Dirección de Envío",
        placeholderNewPassMin: "Contraseña (min 8 carácteres, 1 mayús, 1 num, 1 especial)",
        alertDiscountInvalid: "Código de descuento inválido.",
        alertDiscountApplied: "¡Descuento aplicado!",
        strengthLabel: "Fortaleza",
        strengthWeak: "Débil",
        strengthMedium: "Medio",
        strengthStrong: "Fuerte",
        strengthVeryStrong: "Muy Fuerte",
        alertPasswordRequirements: "La contraseña debe tener al menos 8 caracteres, con 1 mayúscula, 1 número y 1 carácter especial",
        alertEmailPasswordRequired: "Correo y contraseña son requeridos",
        alertRegisterRequired: "Correo, Contraseña, Teléfono y Dirección son requeridos.",
        alertEmailRequired: "Correo es requerido",
        alertPasswordsDoNotMatch: "Las contraseñas no coinciden",
        alertRegistrationSuccess: "¡Registro exitoso! Por favor inicia sesión.",
        alertRegistrationFailed: "Registro fallido.",
        alertLoginFailed: "Inicio de sesión fallido.",
        alertVerifyEmail: "Tu correo no está verificado. ¿Quieres enviar un nuevo código?",
        alertVerificationSent: "¡Código de verificación enviado! Revisa tu correo.",
        alertResetError: "Error enviando enlace de restablecimiento.",
        alertNetworkError: "Error de red.",
        alertPasswordChanged: "¡Contraseña cambiada exitosamente!",
        alertFillPasswordFields: "Por favor llena ambos campos de contraseña.",
        loadingLogin: "Iniciando sesión...",
        loadingRegister: "Registrando...",
        loadingSending: "Enviando...",
        loadingChangingPass: "Cambiando contraseña...",
        searchPlaceholder: "Buscar...",
        discountCode: "Código de Descuento",
        apply: "Aplicar",
        subtotal: "Subtotal",
        discount: "Descuento",
        removeDiscount: "Eliminar descuento",
        checkingStock: "Verificando Stock...",
        outOfStockRemoved: "Los siguientes artículos están agotados y han sido eliminados de tu carrito:",
        paymentError: "Ocurrió un error durante el pago.",
        paymentCancel: "Pago Cancelado",
        alertShippingAddressRequired: "Por favor, proporcione una dirección de envío antes de pagar.",
        alertNoActiveDiscounts: "No tienes descuentos activos.",
        alertDiscountNotAssigned: "Código de descuento no encontrado en tu cuenta.",
        alertDiscountNotActive: "El código de descuento no está activo.",
        alertCartItemsRemoved: "Algunos artículos fueron eliminados de tu carrito porque ya no están disponibles.",
        alertTransactionSuccess: "¡Transacción completada por {name}!",
        alertPaymentSavedError: "Pago exitoso, pero hubo un error guardando el recibo.",
        alertProfileUpdated: "¡Perfil actualizado exitosamente!",
        errorValidatingDiscount: "Error validando el código de descuento.",
        dragDropImage: "Arrastra y Suelta Imagen Aquí",
        clickDropReplace: "Clic o Soltar para Reemplazar",
        noResultsTitle: "¡Lo sentimos! No pudimos encontrar lo que buscas.",
        noResultsText: "Intenta ajustar tus términos de búsqueda.",
        labelMatchName: "Nombre",
        labelMatchSci: "Científico",
        labelMatchPrice: "Precio",
        labelMatchSku: "SKU",
        labelMatchMatched: "Coincidencia",
        btnOtherPayment: "Otro Pago",
        modalOtherPaymentTitle: "Pago Manual",
        labelReceiptImage: "Imagen del Recibo",
        dropReceiptHere: "Arrastra el recibo aquí, pega (Ctrl+V), o haz clic para subir",
        btnConfirmPurchase: "Confirmar Compra",
        alertReceiptRequired: "Por favor sube una imagen del recibo.",
        alertManualOrderSuccess: "¡Orden realizada con éxito! Revisaremos tu recibo.",
        btnOrders: "Pedidos",
        ordersTitle: "Pedidos Pendientes",
        noOrders: "No se encontraron pedidos pendientes.",
        noOrdersFound: "No se encontraron {0}.",
        headerOrder: "Pedido",
        headerCustomer: "Cliente",
        headerTotal: "Total",
        headerStatus: "Estado",
        headerShipped: "¿Enviado?",
        btnUpdateOrders: "Actualizar Pedidos",
        alertOrdersUpdated: "¡Pedidos actualizados exitosamente!",
        viewReceipt: "Ver Recibo",
        btnVerify: "Verificar Pago",
        btnUnverify: "Desverificar Pago",
        receiptModalTitle: "Verificar Recibo",
        alertOrderVerified: "¡Orden verificada! Estado actualizado a procesando.",
        alertOrderUnverified: "¡Orden desverificada! Estado actualizado a verificación manual.",
        labelPayPal: "Info PayPal",
        labelUser: "Info Usuario",
        labelShipping: "Envío",
        labelDate: "Fecha de Creación",
        labelShippedAt: "Fecha de Envío",
        statusActive: "Acción Requerida",
        statusAll: "Todos los Pedidos",
        statusShipped: "Pedidos Enviados",
        statusCancelled: "Pedidos Cancelados",
        statusRefunded: "Pedidos Reembolsados",
        statusPending: "Pago Pendiente",
        statusManual: "Verificación Manual",
        btnShip: "Enviar Pedido",
        btnCancelOrder: "Cancelar Pedido",
        alertOrderShipped: "¡Pedido marcado como enviado!",
        alertOrderCancelled: "Pedido cancelado e inventario restaurado.",
        confirmShip: "¿Marcar este pedido como enviado?",
        confirmCancelOrder: "¿Estás seguro de cancelar este pedido? El inventario será restaurado.",
        alertMinSubtotal: "El subtotal del carrito debe ser de al menos ${usd} / ₡{crc}.",
        labelCode: "Código",
        labelTotal: "Total",
        labelItems: "Artículos",
        loadingItems: "Cargando artículos...",
        btnClose: "Cerrar",
        labelPayPalId: "ID PayPal",
        noItemsInOrder: "No se encontraron artículos para este pedido.",
        errorLoadingItems: "Error cargando artículos.",
        alertReceiptUploadFailed: "Error al subir recibo: ",
        alertOrderPlacementFailed: "Error al realizar pedido: ",
        alertPaymentSystemError: "Error cargando sistema de pago. Por favor intente de nuevo.",
        alertPaymentConfigError: "Falta configuración de pago (Client ID).",
        noAddressProvided: "Dirección no proporcionada",
        alertLoginError: "Error de inicio de sesión: ",
        alertRegistrationError: "Error de registro: ",
        alertVerificationSendError: "Error al enviar código de verificación",
        unknownError: "Error desconocido",
        contactTitle: "Contáctanos",
        labelSubject: "Asunto",
        labelMessage: "Mensaje",
        btnSend: "Enviar",
        alertMessageSent: "¡Mensaje enviado exitosamente!",
        alertMessageFailed: "Error al enviar mensaje.",
        contactBtn: "Contáctanos",
    }
};
