import { Translations } from './types.js';

export const APP_VERSION = '1.0.0';
export const DEFAULT_IMG_CACHE = 100;
export const MAX_IMGS = 1000;
export const MAX_IMG_CACHE_PERCENT = 0.25;

export const PLANT_CLASSES = ["All", "Opuntia", "Euphorbia", "Mammillaria", "Aizoaceae", "Aloe", "Crassula", "Echeveria", "Haworthia", "Sansevieria", "Sedum", "Sempervivum"];

export const translations: Translations = {
    en: {
        logout: "Logout",
        addItem: "Add Item",
        help: "Help",
        cart: "Cart",
        heroTitle: "Rare & Exotic Cacti",
        heroSubtitle: "Delivered safely from our nursery to your doorstep.",
        inventoryTitle: "Current Inventory",
        uploadTitle: "Upload New Cactus",
        labelName: "Cactus Name",
        labelPrice: "Price ($)",
        labelImage: "Image URL",
        helperText: "(For demo, right click any image on Google Images and 'Copy Image Address')",
        btnAddInventory: "Add to Inventory",
        btnUpdateProduct: "Update Product",
        btnCancel: "Cancel",
        btnSave: "Save",
        loginTitle: "Cactus Studio Login",
        loginPlaceholder: "Enter WhatsApp Number",
        btnLogin: "Login",
        cartTitle: "CART",
        btnRemoveAll: "Remove All",
        cartEmpty: "Your cart is empty.",
        cartTotal: "TOTAL:",
        btnCheckout: "CHECKOUT",
        btnAddCart: "Add to Cart",
        btnRemove: "Remove",
        alertAccessGranted: "Admin access granted.",
        alertIncorrectPass: "Incorrect Password.",
        alertValidNumber: "Please enter a valid number.",
        alertUpdated: "Cactus updated!",
        alertAdded: "Cactus added to inventory!",
        alertFillFields: "Please fill in all fields.",
        alertPayment: "This would go to payment!",
        prev: "Prev",
        next: "Next",
        modalAddCart: "Add to Cart +",
        outOfStock: "Out of Stock",
        btnSync: "Sync DB",
        btnMigrate: "Run Migration",
        btnUploadImages: "Upload Images",
        btnUpload: "📤 Upload",
        btnPrev: "Prev",
        btnNext: "Next",
        opt5Page: "5 / page",
        opt10Page: "10 / page",
        opt20Page: "20 / page",
        noAccount: "Don't have an account?",
        registerLink: "Register here",
        hasAccount: "Already have an account?",
        loginLink: "Login here",
        registerTitle: "Create Account",
        btnRegister: "Register",
        filterLabel: "Filter:",
        allOption: "All",
        alertLangChange: "Changing language will log you out and reload the page. Continue?",
        btnProfile: "Profile",
        profileTitle: "My Profile",
        labelPhone: "Phone",
        labelAddress: "Shipping Address",
        btnSaveProfile: "Save Changes",
        changePasswordTitle: "Change Password",
        labelCurrentPassword: "Current Password",
        labelNewPassword: "New Password",
        btnChangePassword: "Update Password",
        forgotPasswordLink: "Forgot Password?",
        resetPasswordTitle: "Reset Password",
        resetPasswordDesc: "Enter your email to receive a reset link.",
        btnSendReset: "Send Reset Link",
        backToLogin: "Back to Login",
        alertResetSent: "If an account exists with that email, a reset link has been sent.",
        placeholderEmail: "Email",
        placeholderPassword: "Password",
        placeholderPasswordConfirm: "Confirm Password",
        placeholderName: "Full Name",
        placeholderAddress: "Shipping Address",
        placeholderNewPassMin: "Password (min 6 chars)"
    },
    es: {
        logout: "Cerrar Sesión",
        addItem: "Agregar Item",
        help: "Ayuda",
        cart: "Carrito",
        heroTitle: "Cactus Raros y Exóticos",
        heroSubtitle: "Entregados con seguridad desde nuestro vivero a tu puerta.",
        inventoryTitle: "Inventario Actual",
        uploadTitle: "Subir Nuevo Cactus",
        labelName: "Nombre del Cactus",
        labelPrice: "Precio ($)",
        labelImage: "URL de Imagen",
        helperText: "(Para demo, clic derecho en cualquier imagen de Google y 'Copiar dirección de imagen')",
        btnAddInventory: "Agregar al Inventario",
        btnUpdateProduct: "Actualizar Producto",
        btnCancel: "Cancelar",
        btnSave: "Guardar",
        loginTitle: "Login Cactus Studio",
        loginPlaceholder: "Ingresa número de WhatsApp",
        btnLogin: "Entrar",
        cartTitle: "CARRITO",
        btnRemoveAll: "Vaciar Carrito",
        cartEmpty: "Tu carrito está vacío.",
        cartTotal: "TOTAL:",
        btnCheckout: "PAGO",
        btnAddCart: "Agregar al Carrito",
        btnRemove: "Eliminar",
        alertAccessGranted: "Acceso de admin concedido.",
        alertIncorrectPass: "Contraseña incorrecta.",
        alertValidNumber: "Por favor ingresa un número válido.",
        alertUpdated: "¡Cactus actualizado!",
        alertAdded: "¡Cactus agregado al inventario!",
        alertFillFields: "Por favor llena todos los campos.",
        alertPayment: "¡Esto iría al pago!",
        prev: "Ant",
        next: "Sig",
        modalAddCart: "Agregar al Carrito +",
        outOfStock: "Agotado",
        btnSync: "Sincronizar BD",
        btnMigrate: "Ejecutar Migración",
        btnUploadImages: "Subir Imágenes",
        btnUpload: "📤 Subir",
        btnPrev: "Ant",
        btnNext: "Sig",
        opt5Page: "5 / pág",
        opt10Page: "10 / pág",
        opt20Page: "20 / pág",
        noAccount: "¿No tienes cuenta?",
        registerLink: "Regístrate aquí",
        hasAccount: "¿Ya tienes cuenta?",
        loginLink: "Inicia sesión aquí",
        registerTitle: "Crear Cuenta",
        btnRegister: "Registrar",
        filterLabel: "Filtrar:",
        allOption: "Todos",
        alertLangChange: "Cambiar el idioma cerrará la sesión y recargará la página. ¿Continuar?",
        btnProfile: "Perfil",
        profileTitle: "Mi Perfil",
        labelPhone: "Teléfono",
        labelAddress: "Dirección de Envío",
        btnSaveProfile: "Guardar Cambios",
        changePasswordTitle: "Cambiar Contraseña",
        labelCurrentPassword: "Contraseña Actual",
        labelNewPassword: "Nueva Contraseña",
        btnChangePassword: "Actualizar Contraseña",
        forgotPasswordLink: "¿Olvidaste tu contraseña?",
        resetPasswordTitle: "Restablecer Contraseña",
        resetPasswordDesc: "Ingresa tu email para recibir un enlace.",
        btnSendReset: "Enviar Enlace",
        backToLogin: "Volver al Login",
        alertResetSent: "Si existe una cuenta con ese email, se ha enviado un enlace.",
        placeholderEmail: "Correo Electrónico",
        placeholderPassword: "Contraseña",
        placeholderPasswordConfirm: "Confirmar Contraseña",
        placeholderName: "Nombre Completo",
        placeholderAddress: "Dirección de Envío",
        placeholderNewPassMin: "Contraseña (min 6 carácteres)"
    }
};
